# Generated by Django 4.0.5 on 2022-07-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0007_alter_funcionario_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
    ]
